idle_fg = "#c8c093"
idle_bg = "#16161d"
info_fg = "#6a9589"
info_bg = "#16161d"
good_fg = "#c8c093"
good_bg = "#16161d"
warning_bg = "#16161d"
warning_fg = "#c0a36e"
critical_bg = "#16161d"
critical_fg = "#c34043"
separator = "|"
separator_bg = "auto"
separator_fg = "#c8c093"
