icons_format = "{icon}"

[theme]
theme = "/home/davisc/.config/status-rs/zenbones-light-colors.toml"

[icons]
icons = "material-nf"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d,  %R') "

[[block]]
block = "notify"
driver = "swaync"
format = " $icon {$notification_count |}"

[[block]]
block = "battery"
driver = "upower"
format = " $icon $percentage "
good = 40
empty_threshold = 0
info = 40

[[block]]
block = "net"
# format = " $icon {$signal_strength / $ssid $frequency|VPN|Ethernet} "
format = " $icon "
error_format = "   "

[[block]]
block = "memory"
# format = " $icon $mem_used_percents.eng(w:1) "
format = " $icon $mem_used.eng(w:1) " 
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "

# [[block]]
# block = "packages"
# package_manager = ["pacman", "aur"]
# interval = 600
# error_interval = 300
# format = "  $total "
# format_singular = "  $total "
# format_up_to_date = "   "
# aur_command = "paru -Qua"
# error_format = "   " 

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"
