idle_fg = "#BBBBBB"
idle_bg = "#303030"
info_fg = "#BBBBBB"
info_bg = "#303030"
good_fg = "#BBBBBB"
good_bg = "#303030"
warning_bg = "#303030"
warning_fg = "#BBBBBB"
critical_bg = "#303030"
critical_fg = "#BBBBBB"
separator = "|"
separator_bg = "auto"
separator_fg = "#BBBBBB"
