idle_bg = "#c1c1c1"
idle_fg = "#252525"
info_bg = "#c1c1c1"
info_fg = "#252525"
good_bg = "#c1c1c1"
good_fg = "#252525"
warning_fg = "#252525"
warning_bg = "#c1c1c1"
critical_fg = "#252525"
critical_bg = "#a02020"
separator = ""
separator_fg = "#252525"
separator_bg = "#c1c1c1"
