idle_fg = "#e8e8d3"
idle_bg = "#252525"
info_fg = "#e8e8d3"
info_bg = "#252525"
good_fg = "#e8e8d3"
good_bg = "#252525"
warning_bg = "#252525"
warning_fg = "#ffb964"
critical_bg = "#252525"
critical_fg = "#cf6a4c"
separator = ""
separator_bg = "auto"
separator_fg = "#e8e8d3"
