idle_fg = "#e8e8d3"
idle_bg = "#1c1c1c"
info_fg = "#e8e8d3"
info_bg = "#1c1c1c"
good_fg = "#e8e8d3"
good_bg = "#1c1c1c"
warning_bg = "#1c1c1c"
warning_fg = "#e8e8d3"
critical_bg = "#1c1c1c"
critical_fg = "#902020"
separator = ""
separator_bg = "auto"
separator_fg = "#e8e8d3"
