idle_bg = "#c1c1c1"
idle_fg = "#54433a"
info_bg = "#c1c1c1"
info_fg = "#54433a"
good_bg = "#c1c1c1"
good_fg = "#54433a"
warning_fg = "#54433a"
warning_bg = "#c1c1c1"
critical_fg = "#54433a"
critical_bg = "#c1c1c1"
separator = "|"
separator_fg = "#54433a"
separator_bg = "#c1c1c1"
