idle_fg = "#ECE1D7"
idle_bg = "#252525"
info_fg = "#ECE1D7"
info_bg = "#252525"
good_fg = "#ECE1D7"
good_bg = "#252525"
warning_bg = "#252525"
warning_fg = "#ECE1D7"
critical_bg = "#252525"
critical_fg = "#ECE1D7"
separator = ""
separator_bg = "auto"
separator_fg = "#ECE1D7"
