idle_bg = "#e9e1db"
idle_fg = "#54433a"
info_bg = "#e9e1db"
info_fg = "#54433a"
good_bg = "#e9e1db"
good_fg = "#54433a"
warning_fg = "#54433a"
warning_bg = "#e9e1db"
critical_fg = "#54433a"
critical_bg = "#e9e1db"
separator = ""
separator_fg = "#54433a"
separator_bg = "#e9e1db"
