icons_format = "{icon}"

[theme]
theme = "/home/davisc/.config/status-rs/melange/melange-light-colors.toml"



[icons]
icons = "material-nf"

[icons.overrides]
music_play = "\U000f03e4" # nf-md-pause
music_pause = "\U000f040a" # nf-md-play
bat = [
    "󱊡",
    "󱊢",
    "󱊣",
]
bat_charging = "󱐋"

[[block]]
block = "music"
format = "{ $play $title.str(max_w:20) - $artist.str(max_w:20) |}"

[[block]]
block = "notify"
driver = "swaync"
format = "{ $icon $notification_count |}"

[[block]]
block = "time"
interval = 5
# format = " $timestamp.datetime(f:'%a %m/%d,  %R') "
format = " $timestamp.datetime(f:' %R') "

[[block]]
block = "time"
interval = 5
# format = " $timestamp.datetime(f:'%a %m/%d,  %R') "
format = " $timestamp.datetime(f:' %a %m/%d') "
# [[block]]
# block = "taskwarrior"
# interval = 60
# format = "  $count.eng(w:1) "
# format_singular = "  1 "
# format_everything_done = "   "
# warning_threshold = 10
# critical_threshold = 20
#
# [[block.filters]]
# name = "today"
# filter = "+PENDING -OVERDUE or +DUETODAY "
# [[block]]
# block = "taskwarrior"
# interval = 60
# format = " 󰀦 $count "
# format_singular = " 󰀦 1 "
# format_everything_done = ""
# warning_threshold = 1
# critical_threshold = 1
#
# [[block.filters]]
# name = "late"
# filter = " +OVERDUE -DUETODAY "

[[block]]
block = "battery"
format = " $icon $percentage "
good = 40
warning = 20
critical = 10
empty_threshold = 5
info = 40


[[block]]
block = "net"
format = " {󰤉 $signal_strength|󰈀} "
inactive_format = " 󰣽 Down "
error_format = "   "

[[block]]
block = "memory"
# format = " $icon $mem_used_percents.eng(w:1) "
format = " 󰍛 $mem_used.eng(w:1) " 
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 3
format = " $icon $barchart $utilization "
# [[block]]
# block = "packages"
# package_manager = ["pacman", "aur"]
# interval = 600
# error_interval = 300
# format = "  $total "
# format_singular = "  $total "
# format_up_to_date = "   "
# aur_command = "paru -Qua"
# error_format = "   " 
[[block]]
block = "temperature"
format = " $icon {$average}μ: $max "
interval = 10
chip = "*-isa-*"

[[block]]
block = "sound"
format = " $icon {$volume|} "
[[block]]
block = "backlight"
device = "intel_backlight"

