idle_fg = "#545464"
idle_bg = "#d2cc9c"
info_fg = "#597b75"
info_bg = "#d2cc9c"
good_fg = "#545464"
good_bg = "#d2cc9c"
warning_bg = "#d2cc9c"
warning_fg = "#77713f"
critical_bg = "#d2cc9c"
critical_fg = "#c84053"
separator = "|"
separator_bg = "auto"
separator_fg = "#545464"
