idle_fg = "#BBBBBB"
idle_bg = "#1e2220"
info_fg = "#6099C0"
info_bg = "#1e2220"
good_fg = "#BBBBBB"
good_bg = "#1e2220"
warning_bg = "#1e2220"
warning_fg = "#B77E64"
critical_bg = "#1e2220"
critical_fg = "#de6e7c"
separator = "|"
separator_bg = "auto"
separator_fg = "#BBBBBB"
