idle_fg = "#B4BDC3"
idle_bg = "#16161d"
info_fg = "#6a9589"
info_bg = "#16161d"
good_fg = "#B4BDC3"
good_bg = "#16161d"
warning_bg = "#16161d"
warning_fg = "#D68C67"
critical_bg = "#16161d"
critical_fg = "#E8838F"
separator = "|"
separator_bg = "auto"
separator_fg = "#B4BDC3"
