idle_bg = "#BBBBBB"
idle_fg = "#353535"
info_bg = "#BBBBBB"
info_fg = "#353535"
good_bg = "#BBBBBB"
good_fg = "#353535"
warning_fg = "#353535"
warning_bg = "#BBBBBB"
critical_fg = "#353535"
critical_bg = "#BBBBBB"
separator = "|"
separator_fg = "#353535"
separator_bg = "#BBBBBB"
