idle_fg = "#ECE1D7"
idle_bg = "#403A36"
info_fg = "#ECE1D7"
info_bg = "#403A36"
good_fg = "#ECE1D7"
good_bg = "#403A36"
warning_bg = "#403A36"
warning_fg = "#ECE1D7"
critical_bg = "#403A36"
critical_fg = "#ECE1D7"
separator = "|"
separator_bg = "auto"
separator_fg = "#ECE1D7"
