idle_fg = "#ffffff"
idle_bg = "#16181a"
info_fg = "#ffffff"
info_bg = "#16181a"
good_fg = "#ffffff"
good_bg = "#16181a"
warning_bg = "#16181a"
warning_fg = "#f1ff5e"
critical_bg = "#16181a"
critical_fg = "#ff6e5e"
separator = ""
separator_bg = "auto"
separator_fg = "#ffffff"
