idle_fg = "#ebdbb2"
idle_bg = "#282828"
info_fg = "#ebdbb2"
info_bg = "#282828"
good_fg = "#ebdbb2"
good_bg = "#282828"
warning_bg = "#282828"
warning_fg = "#ebdbb2"
critical_bg = "#282828"
critical_fg = "#cc241d"
separator = "│"
separator_bg = "auto"
separator_fg = "#ebdbb2"
