idle_fg = "#bdbdbd"
idle_bg = "#202020"
info_fg = "#bdbdbd"
info_bg = "#202020"
good_fg = "#bdbdbd"
good_bg = "#202020"
warning_bg = "#202020"
warning_fg = "#bdbdbd"
critical_bg = "#202020"
critical_fg = "#ff5d5d"
separator = ""
separator_bg = "auto"
separator_fg = "#bdbdbd"
